# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties

spring:
  datasource:
    # url: jdbc:mysql://${DB_MYSQL_DESAENV04_DBFINALPRO_DBFINALPRO_ENDPOINT}/dbfinalpro?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    host: DB_MYSQL_DESAENV04_DBFINALPRO_DBFINALPRO_ENDPOINT
    db: dbfinalpro
    username: dbfinalpro_WPROD
    password: DB_MYSQL_DESAENV04_DBFINALPRO_DBFINALPRO_WPROD
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      sql: debug
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
